In [1]:
import numpy as np
import pandas as pd
import os
#importing basic library for preprocessing

In [2]:
data=pd.read_csv("EncodedVarScore.csv") #reading data

In [3]:
data.head()

0_A  0_C  0_G  0_I  0_T    1  2_A  2_C  2_G  2_I  ...  396_G  396_I  396_T  \
0    0    0    0    0    1  0.0    0    0    0    0  ...      0      0      1   
1    1    0    0    0    0  0.0    1    0    0    0  ...      0      0      1   
2    0    1    0    0    0  0.0    0    0    0    0  ...      0      0      1   
3    0    0    1    0    0  0.0    0    1    0    0  ...      0      0      0   
4    0    0    0    0    1  0.0    0    1    0    0  ...      0      1      0   

     397  398_A  398_C  398_G  398_I  398_T    399  
0   0.00      0      0      1      0      0   0.00  
1   0.00      0      1      0      0      0   0.00  
2   0.00      0      0      0      1      0  61.67  
3   0.00      0      0      0      0      1   0.00  
4  59.25      0      0      1      0      0   0.00  

[5 rows x 1197 columns]

In [4]:
x=data.values#converting into array

In [5]:
x

array([[ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , ...,  1.  ,  0.  , 61.67],
       ...,
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , ...,  0.  ,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , ...,  0.  ,  0.  ,  0.  ]])

In [6]:
y=pd.read_csv("y_data")

In [7]:
y=y.values[:,1]

In [8]:
y

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1])

In [9]:
data.isnull().any() #checking for null values

0_A      False
0_C      False
0_G      False
0_I      False
0_T      False
1        False
2_A      False
2_C      False
2_G      False
2_I      False
2_T      False
3        False
4_A      False
4_C      False
4_G      False
4_I      False
4_T      False
5        False
6_A      False
6_C      False
6_G      False
6_I      False
6_T      False
7        False
8_A      False
8_C      False
8_G      False
8_T      False
9        False
10_A     False
         ...  
390_A    False
390_C    False
390_G    False
390_I    False
390_T    False
391       True
392_A    False
392_C    False
392_G    False
392_I    False
392_T    False
393      False
394_A    False
394_C    False
394_G    False
394_I    False
394_T    False
395      False
396_A    False
396_C    False
396_G    False
396_I    False
396_T    False
397      False
398_A    False
398_C    False
398_G    False
398_I    False
398_T    False
399      False
Length: 1197, dtype: bool

In [10]:
data["391"].isnull().any() #individually checking null values

True

In [11]:
c=[]
for i in data:
    if data[i].isnull().any():
        c.append(i)
#getting to list of column for nulll values

In [12]:
c

['31',
 '33',
 '57',
 '61',
 '83',
 '89',
 '91',
 '101',
 '107',
 '131',
 '133',
 '179',
 '251',
 '269',
 '281',
 '295',
 '305',
 '335',
 '371',
 '391']

In [13]:
c.reverse()

In [14]:
for i in c:
    data=data.drop(i,axis=1)
#dropping null columns from back direction in order to prevent column number change

In [15]:
data

0_A  0_C  0_G  0_I  0_T     1  2_A  2_C  2_G  2_I  ...  396_G  396_I  \
0     0    0    0    0    1   0.0    0    0    0    0  ...      0      0   
1     1    0    0    0    0   0.0    1    0    0    0  ...      0      0   
2     0    1    0    0    0   0.0    0    0    0    0  ...      0      0   
3     0    0    1    0    0   0.0    0    1    0    0  ...      0      0   
4     0    0    0    0    1   0.0    0    1    0    0  ...      0      1   
5     0    0    1    0    0   0.0    0    0    1    0  ...      0      1   
6     0    0    0    1    0  65.0    1    0    0    0  ...      1      0   
7     0    0    0    0    1   0.0    0    1    0    0  ...      0      1   
8     0    0    0    1    0  60.0    0    1    0    0  ...      1      0   
9     0    0    1    0    0   0.0    0    0    0    0  ...      0      0   
10    0    0    0    1    0  63.0    0    0    1    0  ...      0      0   
11    1    0    0    0    0   0.0    1    0    0    0  ...      0      0   
12    0    0    1    0    0   0.0    1    0    0    0  ...      0      0   
13    0    0    1    0    0   0.0    0    0    0    0  ...      0      0   
14    0    0    0    0    1   0.0    0    1    0    0  ...      0      0   
15    0    1    0    0    0   0.0    0    0    0    1  ...      0      0   
16    0    0    0    1    0  59.8    1    0    0    0  ...      1      0   
17    0    0    1    0    0   0.0    0    0    0    0  ...      0      0   
18    1    0    0    0    0   0.0    0    0    0    1  ...      0      0   
19    0    1    0    0    0   0.0    0    0    1    0  ...      0      0   
20    0    0    1    0    0   0.0    0    1    0    0  ...      0      1   
21    1    0    0    0    0   0.0    0    1    0    0  ...      1      0   
22    0    0    0    0    1   0.0    0    0    0    0  ...      0      0   
23    0    0    0    0    1   0.0    0    1    0    0  ...      0      0   
24    1    0    0    0    0   0.0    1    0    0    0  ...      0      0   
25    0    0    0    0    1   0.0    0    0    0    0  ...      0      0   
26    0    1    0    0    0   0.0    1    0    0    0  ...      0      0   
27    1    0    0    0    0   0.0    1    0    0    0  ...      0      0   
28    0    0    1    0    0   0.0    0    0    1    0  ...      0      0   
29    1    0    0    0    0   0.0    0    0    1    0  ...      0      0   
30    0    0    0    0    1   0.0    1    0    0    0  ...      1      0   
31    0    0    0    0    1   0.0    0    1    0    0  ...      0      0   
32    0    1    0    0    0   0.0    1    0    0    0  ...      0      0   
33    0    0    0    0    1   0.0    1    0    0    0  ...      0      0   
34    0    0    1    0    0   0.0    0    0    0    0  ...      0      1   
35    0    0    0    1    0  60.6    0    1    0    0  ...      0      0   
36    0    0    1    0    0   0.0    0    1    0    0  ...      0      0   
37    0    0    0    1    0  48.0    0    1    0    0  ...      0      0   
38    0    1    0    0    0   0.0    0    0    0    0  ...      0      0   
39    0    1    0    0    0   0.0    0    1    0    0  ...      0      0   

    396_T    397  398_A  398_C  398_G  398_I  398_T    399  
0       1   0.00      0      0      1      0      0   0.00  
1       1   0.00      0      1      0      0      0   0.00  
2       1   0.00      0      0      0      1      0  61.67  
3       0   0.00      0      0      0      0      1   0.00  
4       0  59.25      0      0      1      0      0   0.00  
5       0  68.25      0      0      0      0      1   0.00  
6       0   0.00      0      0      1      0      0   0.00  
7       0  49.75      1      0      0      0      0   0.00  
8       0   0.00      0      0      1      0      0   0.00  
9       0   0.00      0      0      1      0      0   0.00  
10      0   0.00      0      0      1      0      0   0.00  
11      0   0.00      0      0      0      1      0  59.67  
12      0   0.00      0      1      0      0      0   0.00  
13      0   0.00      0      1   

In [18]:
x=data.values

In [19]:
x

array([[ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 1.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , ...,  1.  ,  0.  , 61.67],
       ...,
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , ...,  0.  ,  1.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  , ...,  0.  ,  0.  ,  0.  ]])

#### applying neural layer

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.3,random_state=10)

In [22]:
xtrain

array([[0., 0., 1., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [27]:
from sklearn.svm import SVC

 from sklearn.model_selection import GridSearchCV

param_grid = {'kernel': ['linear','poly','rbf','sigmoid']}

In [40]:
clf=SVC()

In [41]:
clf.fit(xtrain,ytrain)

/home/satyanveshi/.local/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [42]:
clf.predict(xtest)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [43]:
pd.crosstab(ytest,ypred)

col_0  1
row_0   
0      4
1      8

##### support vector is not giving suitable results